language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-beta
    - git
node_js:
- '7'
before_script:
- npm install -g surge
- npm run build
script:
- surge dist/ https://monitor.hplustime.com --token $SURGE_TOKEN
