language: node_js
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-beta
    - git
node_js:
- '7'
before_script:
- npm install -g vue-cli lighthouse surge
- npm run build
script:
- cp .surgeignore build/default
- cp -r til build/default
- surge build/default monitor.hplustime.com --token $SURGE_TOKEN
- mkdir report && cp README.md report
- lighthouse --chrome-flags="--disable-gpu --headless" https://monitor.hplustime.com --output html --output-path=report/index.html
- echo audit.hplustime.com > report/CNAME
- surge report audit.hplustime.com --token $SURGE_TOKEN